/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("template.java-library-conventions")
    id("template.java-test-conventions")
    id("template.java-code-quality-conventions")
}

dependencies {
    api(project(":list"))
}
