/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("template.java-application-conventions")
    id("template.java-test-conventions")
    id("template.java-code-quality-conventions")
}

dependencies {
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("template.app.App")
}
