/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package template.utilities;

import template.list.LinkedList;

public final class StringUtils {

    private StringUtils() {
    }

    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
