/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package template.app;

import template.list.LinkedList;

import static template.app.MessageUtils.getMessage;
import static template.utilities.StringUtils.join;
import static template.utilities.StringUtils.split;

public final class App {
    private App() {

    }

    /**
     * Main entry point to the application.
     *
     * @param args string arguments passed in via the command line
     */
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));       //NOPMD
    }
}
