/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package template.app;

final class MessageUtils {
    private MessageUtils() {
    }

    public static String getMessage() {
        return "Hello      World!";
    }
}
